# These hoists are needed for @dhis2/app-shell since it uses directly some libraries that were hoisted by yarn 1
# This is a better alternative than pnpm's shamefullyHoist https://pnpm.io/settings#shamefullyhoist until we update the way that @dhis2/app-shell works
publicHoistPattern:
  - "@dhis2/ui"
  - "typeface-roboto"
  - "@dhis2/app-adapter"
  - "prop-types"
  - "@dhis2/d2-i18n"
  - "post-robot"
  - "styled-jsx"

onlyBuiltDependencies:
  - "@dhis2/cli-helpers-engine"
  - core-js-pure
  - esbuild
