version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    version_requirement_updates: "increase_versions_if_necessary"
  - package_manager: "javascript"
    directory: "/examples/simple-app"
    update_schedule: "weekly"
    version_requirement_updates: "increase_versions_if_necessary"
